import type { Metadata } from "next";
import InitializeUser from "@/components/initialize-user";
import Navbar from "@/components/dashboard/navbar";
import { ThemeProvider } from "@/components/context/theme-provider";
import Sidebar from "@/components/dashboard/sidebar";
import MobileNav from "@/components/dashboard/mobile-nav";
import SearchBarContext from "@/components/context/search-bar-context";
import { Toaster } from "sonner";
import { FileUploadToaster } from "@/components/file-upload-toaster";
import SocketListner from "@/components/socket/socket-listner";


export const metadata: Metadata = {
  title: "Dashboard Ex-drive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
       attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
    >
      <FileUploadToaster/>
      <div className="w-full flex  h-full">
        <InitializeUser/>
        <Sidebar/>
        <SocketListner/>
        <section className="flex-1 flex-col h-full">
           <SearchBarContext>
            <Navbar/>
           <MobileNav/>
        {children}
         <div className="w-full h-40"></div>
           </SearchBarContext>
        </section>
        <Toaster richColors closeButton />
    </div>
    </ThemeProvider>
  );
}
